config/routes.rb
#ネットワーク上でデータを転送する際、その経路を導き出すことをルーティング

Rails.application.routes.draw do
  #get.    URL  =>. コントローラ名#アクション名
  
  get 'top' => 'homes#top'
  resources :lists #lists コントローラの同じ名前のアクションに紐づく(どれ)
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_one_attached :image
    
    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
     # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @list = List.new  
  end

 def create #保存 #viewファイルに写す必要が出たから＠verになる　ただの保存ならList=でいい
    @list = List.new(list_params) 
    if @list.save #データをデータベースに保存するためのsaveメソッド実行
     flash[:notice] = "投稿に成功しました。"   # フラッシュメッセージを定義 12章
    redirect_to list_path(@list.id) #listやからshow(詳細に戻る)
     else 
       flash.now[:alert] = "投稿に失敗しました。"
       render:new #renderはアクション名　同じコントローラ内の別アクションのViewを表示できます
     end 
 end 
 


  def index #書籍の巻末の索引のように、多数のものの中から特定の対象をすばやく見つけ出すため識別情報や、整列された所在情報の一覧などを指す
      @lists = List.all #@がついてるからインスタンス変数（自由記載）　ここで指定しておくとview上でインスタンス変数に格納された情報を表示できる
  end

  def show
      @list = List.find(params[:id]) #今回はレコードを1件だけ取得するので、インスタンス変数名は単数形
  end                   #params[:id] は決まり？？
         #allは全て、に対しfindメソッドは引数を受け取り、idカラムを引数と比べてレコードを取得。

  def edit #編集という意味
      @list = List.find(params[:id]) #投稿済みのデータを編集するからfind(s探す)を使う
  end
  
  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)  
  end
  
  def destroy #消去
      list = List.find(params[:id]) #list(データベース)から消す。findで対象探す
      list.destroy #探せたら消す
      redirect_to '/lists' #消せたら戻る。今回は一覧に戻るため'/lists'　getと
  end 
  
  private #プライベート
  #privateは一種の境界線で、「ここから下はこのcontrollerの中でしか呼び出せません」てゆう意味
  #privateより後に定義されたメソッドは、アクションとして認識されなくなり、URLと対応できなくなる
  def 
    list_params #paramsとは、フォームなどによって送られてきた情報（パラメーター）を取得するメソッド
    # ↓がストロングパラメータ。悪質なコードとかを入力されるのを防ぐ人工知能的な。
    params.require(:list).permit(:title, :body,:image) #入力をされる→悪質な悪戯を受ける可能性があるから入力勢（titleとか）この知能を入れとく。
    # require. 送られてきたデータの中からモデル名(ここでは:list)を指定し、データを絞り込みます。
    # permit.   requireで絞り込んだデータの中から、保存を許可するカラムを指定します。
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>
      </ul>
    </nav>
    
    
    <main>     
    <div>
       <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    </div>

    <%= yield %>
    
    </main>
    
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list  do |f| %> <!--基本コード　editやからgetじゃなくてpostになってる？-->

 <h4>タイトル</h4>
 <%= f.text_field :title %>
 
 <h4>本文</h4>
 <%= f.text_area :body %>
 
 <%= f.submit '保存' %>
 <% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
<% @lists.each do |list| %>

  <div class="list-box">
    <% if list.image.attached? %>
      <%= image_tag list.image, size: "200x200" %>
    <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
    <% end %>
    
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <span class="list-title"><%=link_to list.title, list_path(list.id) %></span>
    </div>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>

<% if @list.errors.any? %> <!--errorsは、発生したエラーの内容を確認できるメソッドです。any? と組み合わせると、エラーが発生しているかどうかを判定できる。-->
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %> <!--エラーの数だけメッセージ繰り返してくれる-->
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


 <%= form_with model: @list, url: '/lists', methood: :post do |f| %> 
 <!--@の後ろが大文字なのか小文字なのかが違うだけで合わなくなる-->

  <h4>タイトル</h4>
  <%= f.text_field :title %>
 
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <!--文字通り、ファイルの投稿をするためのフィールド.
  本来は画像ファイル以外の全てのファイル(音声ファイルや動画ファイルなど)も投稿OK
  今回はaccept: "image/*"をつける事で画像のみに指定している-->
  
  <%= f.submit '投稿' %>
  
  <% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
<%= image_tag @list.image, size: "300x300" %> <!--こっちはviewに渡すから＠ついてる-->


<%= link_to "編集",edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>